export interface Product {
  price: number;
  article_name: string;
  article_no: string;
  barcode: string;
  material_type: string;
  brand: string;
  sku_id: string;
  origin_price: number;
  q: number;
  sap_promotion: any[];
  discount: any[];
  net_price: number;
  net_discount: number;
  reference_id: string | null;
  note: string | null;
}

export interface Transaction {
  Plant_code: string;
  Sloc_code: string;
  plant_name: string;
  Channel_code: string | null;
  Channel_name: string | null;
  transaction_type: string;
  invoice_no_ref: string;
  Total: number;
  Invoice_no: string;
  product: Product[];
  header_discount: any[];
  q: number;
  Sales_no: string;
  t_datetime: string;
  member_id: string | null;
  telephone: string;
  external_user_id: string | null;
  external_order_id: string | null;
  external_tracking_no: string | null;
  external_telephone: string | null;
  external_first_name: string | null;
  external_last_name: string | null;
  is_point: number;
  sale_channel_id: number;
  no_point: number;
  transaction_code_id: number;
  service_chargeAmt: number;
  service_charge: number;
  sub_total: number;
  number_of_customer: number;
  sale_firstname: string | null;
  sale_lastname: string | null;
  receipt_url: string | null;
  payment_type: string | null;
  ip: string;
  verifycustomer_type: number;
  external_id: string;
  shipping_cost: number;
  shipping_discount: number;
  document_data: any | null;
  document_type: string | null;
  slip_url: string | null;
  slip_data: any | null;
  slip_type: string | null;
  billing_address: string | null;
  shipping_address: string | null;
  billing_address_transaction: any | null;
  shipping_address_transaction: any | null;
  is_retry: boolean;
  transaction_error_id: number;
  updated_by: string | null;
  source_name: string | null;
  customer_name: string | null;
  status: number;
  center_point: number;
  branch_point: number;
  current_point: number;
  is_edit: number;
}
export interface Customer {
  first_name_th: string | null;
  middle_name_th: string | null;
  last_name_th: string | null;
  telephone: string | null;
  is_consent: number | null;
  birthday: string | null;
  id_card: string | null;
  passport_no: string | null;
  telephone_country_id: number | null;
}
